// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSession = `-- name: CheckSession :one
select s.user_id, s.revoked, s.revoke_at 
from sessions as s 
join users as u on s.user_id = u.id
where session_id = $1 and device_id = $2 and u.is_active = true
`

type CheckSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	DeviceID  uuid.UUID `json:"device_id"`
}

type CheckSessionRow struct {
	UserID   int64              `json:"user_id"`
	Revoked  bool               `json:"revoked"`
	RevokeAt pgtype.Timestamptz `json:"revoke_at"`
}

func (q *Queries) CheckSession(ctx context.Context, arg CheckSessionParams) (CheckSessionRow, error) {
	row := q.db.QueryRow(ctx, checkSession, arg.SessionID, arg.DeviceID)
	var i CheckSessionRow
	err := row.Scan(&i.UserID, &i.Revoked, &i.RevokeAt)
	return i, err
}

const cleanupSessionTable = `-- name: CleanupSessionTable :exec
delete from sessions where revoked = true and revoke_at < now() - interval '1 days'
`

func (q *Queries) CleanupSessionTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupSessionTable)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
insert into api_keys (key_hash) values ($1)
`

// manage apikeys
func (q *Queries) CreateAPIKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, createAPIKey, keyHash)
	return err
}

const oAuthLogin = `-- name: OAuthLogin :one
select f.user_id::bigint, f.session_id::uuid, f.profile_exists::boolean from oauth_login($1, $2, $3, $4, $5) as f
`

type OAuthLoginParams struct {
	PProvider       string    `json:"p_provider"`
	PProviderUserID string    `json:"p_provider_user_id"`
	PDisplayName    string    `json:"p_display_name"`
	PEmail          string    `json:"p_email"`
	PDeviceID       uuid.UUID `json:"p_device_id"`
}

type OAuthLoginRow struct {
	FUserID        int64     `json:"f_user_id"`
	FSessionID     uuid.UUID `json:"f_session_id"`
	FProfileExists bool      `json:"f_profile_exists"`
}

func (q *Queries) OAuthLogin(ctx context.Context, arg OAuthLoginParams) (OAuthLoginRow, error) {
	row := q.db.QueryRow(ctx, oAuthLogin,
		arg.PProvider,
		arg.PProviderUserID,
		arg.PDisplayName,
		arg.PEmail,
		arg.PDeviceID,
	)
	var i OAuthLoginRow
	err := row.Scan(&i.FUserID, &i.FSessionID, &i.FProfileExists)
	return i, err
}

const revokeAPIKeyByKey = `-- name: RevokeAPIKeyByKey :exec
update api_keys set is_active = false, revoked_at = now() where key_hash = $1
`

func (q *Queries) RevokeAPIKeyByKey(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByKey, keyHash)
	return err
}

const revokeAllAPIKeys = `-- name: RevokeAllAPIKeys :exec
update api_keys set is_active = false, revoked_at = now() where is_active = true
`

func (q *Queries) RevokeAllAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, revokeAllAPIKeys)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
update sessions set revoked = true, revoke_at = now() where user_id = $1
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
update sessions set revoked = true, revoke_at = now() where session_id = $1 and device_id = $2
`

type RevokeSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	DeviceID  uuid.UUID `json:"device_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.SessionID, arg.DeviceID)
	return err
}

const validateAPIKey = `-- name: ValidateAPIKey :one
select is_active from api_keys where key_hash = $1
`

func (q *Queries) ValidateAPIKey(ctx context.Context, keyHash string) (bool, error) {
	row := q.db.QueryRow(ctx, validateAPIKey, keyHash)
	var is_active bool
	err := row.Scan(&is_active)
	return is_active, err
}
