// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friend.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequestById = `-- name: AcceptFriendRequestById :one
select a.sender_id::bigint , a.receiver_name::text from accept_friend_request($1, $2) as a
`

type AcceptFriendRequestByIdParams struct {
	PRequestID  int64 `json:"p_request_id"`
	PReceiverID int64 `json:"p_receiver_id"`
}

type AcceptFriendRequestByIdRow struct {
	ASenderID     int64  `json:"a_sender_id"`
	AReceiverName string `json:"a_receiver_name"`
}

func (q *Queries) AcceptFriendRequestById(ctx context.Context, arg AcceptFriendRequestByIdParams) (AcceptFriendRequestByIdRow, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequestById, arg.PRequestID, arg.PReceiverID)
	var i AcceptFriendRequestByIdRow
	err := row.Scan(&i.ASenderID, &i.AReceiverName)
	return i, err
}

const addFriendById = `-- name: AddFriendById :one
select f.status::boolean, f.message::text from send_friend_request($1, $2) as f
`

type AddFriendByIdParams struct {
	PSenderID   int64 `json:"p_sender_id"`
	PReceiverID int64 `json:"p_receiver_id"`
}

type AddFriendByIdRow struct {
	FStatus  bool   `json:"f_status"`
	FMessage string `json:"f_message"`
}

func (q *Queries) AddFriendById(ctx context.Context, arg AddFriendByIdParams) (AddFriendByIdRow, error) {
	row := q.db.QueryRow(ctx, addFriendById, arg.PSenderID, arg.PReceiverID)
	var i AddFriendByIdRow
	err := row.Scan(&i.FStatus, &i.FMessage)
	return i, err
}

const getFriendsList = `-- name: GetFriendsList :many
with friend_ids as (
    select f.user1_id as id from friendships f where f.user2_id = $1
    union all
    select f.user2_id as id from friendships f where f.user1_id = $1
)

select 
    u.uuid, 
    u.user_id,
    coalesce(p.name, u.display_name) as name, 
    p.avatar_url,
    u.is_active
from users u
left join profiles p on u.user_id = p.user_id
join friend_ids f on u.user_id = f.id
order by coalesce(p.name, u.display_name)
`

type GetFriendsListRow struct {
	Uuid      uuid.UUID   `json:"uuid"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) GetFriendsList(ctx context.Context, user2ID int64) ([]GetFriendsListRow, error) {
	rows, err := q.db.Query(ctx, getFriendsList, user2ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendsListRow{}
	for rows.Next() {
		var i GetFriendsListRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingFriendRequests = `-- name: GetPendingFriendRequests :many
select fr.request_id, u.uuid, p.name, p.avatar_url, fr.send_at
from friend_requests fr
join users u on fr.sender_id = u.user_id
left join profiles p on fr.sender_id = p.user_id
where fr.receiver_id = $1 and fr.status = 'pending'
order by fr.send_at desc
`

type GetPendingFriendRequestsRow struct {
	RequestID int64       `json:"request_id"`
	Uuid      uuid.UUID   `json:"uuid"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	SendAt    time.Time   `json:"send_at"`
}

func (q *Queries) GetPendingFriendRequests(ctx context.Context, receiverID int64) ([]GetPendingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getPendingFriendRequests, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingFriendRequestsRow{}
	for rows.Next() {
		var i GetPendingFriendRequestsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.Uuid,
			&i.Name,
			&i.AvatarUrl,
			&i.SendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentFriendRequests = `-- name: GetSentFriendRequests :many
select fr.request_id, u.uuid, p.name, p.avatar_url, fr.send_at
from friend_requests fr
join users u on fr.receiver_id = u.user_id
left join profiles p on fr.receiver_id = p.user_id
where fr.sender_id = $1 and fr.status = 'pending'
order by fr.send_at desc
`

type GetSentFriendRequestsRow struct {
	RequestID int64       `json:"request_id"`
	Uuid      uuid.UUID   `json:"uuid"`
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	SendAt    time.Time   `json:"send_at"`
}

func (q *Queries) GetSentFriendRequests(ctx context.Context, senderID int64) ([]GetSentFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, getSentFriendRequests, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSentFriendRequestsRow{}
	for rows.Next() {
		var i GetSentFriendRequestsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.Uuid,
			&i.Name,
			&i.AvatarUrl,
			&i.SendAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectFriendRequestById = `-- name: RejectFriendRequestById :exec
delete from friend_requests
where request_id = $1 and receiver_id = $2 and status = 'pending'
`

type RejectFriendRequestByIdParams struct {
	RequestID  int64 `json:"request_id"`
	ReceiverID int64 `json:"receiver_id"`
}

func (q *Queries) RejectFriendRequestById(ctx context.Context, arg RejectFriendRequestByIdParams) error {
	_, err := q.db.Exec(ctx, rejectFriendRequestById, arg.RequestID, arg.ReceiverID)
	return err
}

const removeFriendById = `-- name: RemoveFriendById :one
select remove_friend_by_uuid($1, $2) as deleted_count
`

type RemoveFriendByIdParams struct {
	PCurrentUserID int64     `json:"p_current_user_id"`
	PFriendUuid    uuid.UUID `json:"p_friend_uuid"`
}

func (q *Queries) RemoveFriendById(ctx context.Context, arg RemoveFriendByIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeFriendById, arg.PCurrentUserID, arg.PFriendUuid)
	var deleted_count int64
	err := row.Scan(&deleted_count)
	return deleted_count, err
}

const searchFriendByName = `-- name: SearchFriendByName :many
with friend_ids as (
    select f.user1_id as id from friendships f where f.user2_id = $1
    union all
    select f.user2_id as id from friendships f where f.user1_id = $1
)

select 
    u.uuid, 
    u.user_id,
    coalesce(p.name, u.display_name) as name, 
    p.avatar_url,
    u.is_active
from users u
left join profiles p on u.user_id = p.user_id
join friend_ids f on u.user_id = f.id
where coalesce(p.name, u.display_name) ilike '%' || $2 || '%' 
order by coalesce(p.name, u.display_name)
`

type SearchFriendByNameParams struct {
	User2ID int64       `json:"user2_id"`
	Column2 pgtype.Text `json:"column_2"`
}

type SearchFriendByNameRow struct {
	Uuid      uuid.UUID   `json:"uuid"`
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) SearchFriendByName(ctx context.Context, arg SearchFriendByNameParams) ([]SearchFriendByNameRow, error) {
	rows, err := q.db.Query(ctx, searchFriendByName, arg.User2ID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchFriendByNameRow{}
	for rows.Next() {
		var i SearchFriendByNameRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.AvatarUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
