// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMembers = `-- name: AddGroupMembers :one
insert into conversation_members (conversation_id, user_id, role)
select $1, $2, 'member'
where exists (
    select 1 from conversation_members cm
    where cm.conversation_id = $1 and cm.user_id = $3 and cm.role = 'admin'
)
returning conversation_id, user_id, role
`

type AddGroupMembersParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
	UserID_2       int64 `json:"user_id_2"`
}

type AddGroupMembersRow struct {
	ConversationID int64      `json:"conversation_id"`
	UserID         int64      `json:"user_id"`
	Role           MemberRole `json:"role"`
}

func (q *Queries) AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) (AddGroupMembersRow, error) {
	row := q.db.QueryRow(ctx, addGroupMembers, arg.ConversationID, arg.UserID, arg.UserID_2)
	var i AddGroupMembersRow
	err := row.Scan(&i.ConversationID, &i.UserID, &i.Role)
	return i, err
}

const createGroupConversation = `-- name: CreateGroupConversation :one
select c.conversation_id::bigint, c.group_name::text, c.invalid_user_ids::bigint[] from create_group_conversation($1, $2, $3) as c
`

type CreateGroupConversationParams struct {
	PCreatorID int64  `json:"p_creator_id"`
	PGroupName string `json:"p_group_name"`
	PMemberIds int64  `json:"p_member_ids"`
}

type CreateGroupConversationRow struct {
	CConversationID int64   `json:"c_conversation_id"`
	CGroupName      string  `json:"c_group_name"`
	CInvalidUserIds []int64 `json:"c_invalid_user_ids"`
}

func (q *Queries) CreateGroupConversation(ctx context.Context, arg CreateGroupConversationParams) (CreateGroupConversationRow, error) {
	row := q.db.QueryRow(ctx, createGroupConversation, arg.PCreatorID, arg.PGroupName, arg.PMemberIds)
	var i CreateGroupConversationRow
	err := row.Scan(&i.CConversationID, &i.CGroupName, &i.CInvalidUserIds)
	return i, err
}

const getGroupMembers = `-- name: GetGroupMembers :many
select 
    u.uuid, 
    coalesce(p.name, u.display_name) as name, 
    p.avatar_url,
    cm.role
from conversation_members cm
join users u on cm.user_id = u.user_id
left join profiles p on u.user_id = p.user_id
where cm.conversation_id = $1
order by coalesce(p.name, u.display_name)
`

type GetGroupMembersRow struct {
	Uuid      uuid.UUID   `json:"uuid"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Role      MemberRole  `json:"role"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, conversationID int64) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupMembersRow{}
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaveConversation = `-- name: LeaveConversation :one
delete from conversation_members
where conversation_id = $1 and user_id = $2
returning conversation_id, user_id
`

type LeaveConversationParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

type LeaveConversationRow struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
}

func (q *Queries) LeaveConversation(ctx context.Context, arg LeaveConversationParams) (LeaveConversationRow, error) {
	row := q.db.QueryRow(ctx, leaveConversation, arg.ConversationID, arg.UserID)
	var i LeaveConversationRow
	err := row.Scan(&i.ConversationID, &i.UserID)
	return i, err
}

const removeGroupMembers = `-- name: RemoveGroupMembers :exec
delete from conversation_members cm
where cm.conversation_id = $1 and cm.user_id = $2
and exists (
    select 1 from conversation_members cm
    where cm.conversation_id = $1 and cm.user_id = $3 and cm.role = 'admin'
)
`

type RemoveGroupMembersParams struct {
	ConversationID int64 `json:"conversation_id"`
	UserID         int64 `json:"user_id"`
	UserID_2       int64 `json:"user_id_2"`
}

func (q *Queries) RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) error {
	_, err := q.db.Exec(ctx, removeGroupMembers, arg.ConversationID, arg.UserID, arg.UserID_2)
	return err
}

const updateGroupInfo = `-- name: UpdateGroupInfo :one
update groups set 
    name = coalesce($2, name),
    avatar_url = coalesce($3, avatar_url)
where conversation_id = $1
returning conversation_id, name, avatar_url, created_at
`

type UpdateGroupInfoParams struct {
	ConversationID int64       `json:"conversation_id"`
	Name           pgtype.Text `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroupInfo, arg.ConversationID, arg.Name, arg.AvatarUrl)
	var i Group
	err := row.Scan(
		&i.ConversationID,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
