// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, name, email, birthday, avatar_url) VALUES ($1, $2, $3, $4, $5) RETURNING user_id, name, email, phone, birthday, avatar_url, updated_at
`

type CreateProfileParams struct {
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	Birthday  pgtype.Date `json:"birthday"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.Birthday,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Birthday,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserId = `-- name: GetProfileByUserId :one
SELECT p.user_id, p.name, p.email, p.phone, p.birthday, p.avatar_url, p.updated_at, u.uuid
FROM profiles p
join users u on p.user_id = u.user_id
WHERE p.user_id = $1
`

type GetProfileByUserIdRow struct {
	UserID    int64       `json:"user_id"`
	Name      string      `json:"name"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Birthday  pgtype.Date `json:"birthday"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	UpdatedAt time.Time   `json:"updated_at"`
	Uuid      uuid.UUID   `json:"uuid"`
}

func (q *Queries) GetProfileByUserId(ctx context.Context, userID int64) (GetProfileByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserId, userID)
	var i GetProfileByUserIdRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Birthday,
		&i.AvatarUrl,
		&i.UpdatedAt,
		&i.Uuid,
	)
	return i, err
}

const getProfilesByUserUUID = `-- name: GetProfilesByUserUUID :one
SELECT p.name, p.user_id, p.avatar_url
FROM profiles p
JOIN users u ON p.user_id = u.user_id
WHERE u.uuid = $1 AND u.is_active = true
`

type GetProfilesByUserUUIDRow struct {
	Name      string      `json:"name"`
	UserID    int64       `json:"user_id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) GetProfilesByUserUUID(ctx context.Context, argUuid uuid.UUID) (GetProfilesByUserUUIDRow, error) {
	row := q.db.QueryRow(ctx, getProfilesByUserUUID, argUuid)
	var i GetProfilesByUserUUIDRow
	err := row.Scan(&i.Name, &i.UserID, &i.AvatarUrl)
	return i, err
}

const updateProfileByUserId = `-- name: UpdateProfileByUserId :one
UPDATE profiles SET 
    name = COALESCE($2, name),
    birthday = COALESCE($3, birthday),
    email = COALESCE($4, email),
    phone = COALESCE($5, phone),
    avatar_url = COALESCE($6, avatar_url),
    updated_at = now()
WHERE user_id = $1 
RETURNING user_id, name, email, phone, birthday, avatar_url, updated_at
`

type UpdateProfileByUserIdParams struct {
	UserID    int64       `json:"user_id"`
	Name      pgtype.Text `json:"name"`
	Birthday  pgtype.Date `json:"birthday"`
	Email     pgtype.Text `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileByUserId,
		arg.UserID,
		arg.Name,
		arg.Birthday,
		arg.Email,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Birthday,
		&i.AvatarUrl,
		&i.UpdatedAt,
	)
	return i, err
}
