// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptFriendRequestById(ctx context.Context, arg AcceptFriendRequestByIdParams) (AcceptFriendRequestByIdRow, error)
	AddFriendById(ctx context.Context, arg AddFriendByIdParams) (AddFriendByIdRow, error)
	AddGroupMembers(ctx context.Context, arg AddGroupMembersParams) (AddGroupMembersRow, error)
	CheckSession(ctx context.Context, arg CheckSessionParams) (CheckSessionRow, error)
	CleanupSessionTable(ctx context.Context) error
	// manage apikeys
	CreateAPIKey(ctx context.Context, keyHash string) error
	CreateGroupConversation(ctx context.Context, arg CreateGroupConversationParams) (CreateGroupConversationRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSystemMessage(ctx context.Context, arg CreateSystemMessageParams) (CreateSystemMessageRow, error)
	CreateUser(ctx context.Context, displayName string) (User, error)
	GetAllConversations(ctx context.Context, userID int64) ([]GetAllConversationsRow, error)
	GetFriendsList(ctx context.Context, user2ID int64) ([]GetFriendsListRow, error)
	GetGroupMembers(ctx context.Context, conversationID int64) ([]GetGroupMembersRow, error)
	GetMessagesByConversationId(ctx context.Context, arg GetMessagesByConversationIdParams) ([]GetMessagesByConversationIdRow, error)
	GetPendingFriendRequests(ctx context.Context, receiverID int64) ([]GetPendingFriendRequestsRow, error)
	GetProfileByUserId(ctx context.Context, userID int64) (GetProfileByUserIdRow, error)
	GetProfilesByUserUUID(ctx context.Context, argUuid uuid.UUID) (GetProfilesByUserUUIDRow, error)
	GetSentFriendRequests(ctx context.Context, senderID int64) ([]GetSentFriendRequestsRow, error)
	GetUUIDByUserId(ctx context.Context, userID int64) (uuid.UUID, error)
	// Get user info with friendship/friend request status
	// $1: target_user_uuid (user being searched)
	// $2: current_user_id (user doing the search)
	// Check if there's a pending/accepted friend request
	// Check if already friends
	GetUserByUUID(ctx context.Context, arg GetUserByUUIDParams) (GetUserByUUIDRow, error)
	LeaveConversation(ctx context.Context, arg LeaveConversationParams) (LeaveConversationRow, error)
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	OAuthLogin(ctx context.Context, arg OAuthLoginParams) (OAuthLoginRow, error)
	RejectFriendRequestById(ctx context.Context, arg RejectFriendRequestByIdParams) error
	RemoveFriendById(ctx context.Context, arg RemoveFriendByIdParams) (int64, error)
	RemoveGroupMembers(ctx context.Context, arg RemoveGroupMembersParams) error
	RevokeAPIKeyByKey(ctx context.Context, keyHash string) error
	RevokeAllAPIKeys(ctx context.Context) error
	RevokeAllSessions(ctx context.Context, userID int64) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SearchConversationByName(ctx context.Context, arg SearchConversationByNameParams) ([]SearchConversationByNameRow, error)
	SearchFriendByName(ctx context.Context, arg SearchFriendByNameParams) ([]SearchFriendByNameRow, error)
	UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Group, error)
	UpdateProfileByUserId(ctx context.Context, arg UpdateProfileByUserIdParams) (Profile, error)
	ValidateAPIKey(ctx context.Context, keyHash string) (bool, error)
}

var _ Querier = (*Queries)(nil)
