// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name) VALUES ($1) RETURNING user_id, uuid, display_name, created_at, is_active
`

func (q *Queries) CreateUser(ctx context.Context, displayName string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, displayName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.DisplayName,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUUIDByUserId = `-- name: GetUUIDByUserId :one
SELECT uuid FROM users WHERE user_id = $1
`

func (q *Queries) GetUUIDByUserId(ctx context.Context, userID int64) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUUIDByUserId, userID)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT 
    u.user_id,
    u.uuid,
    u.display_name,
    
    -- Friend request status (if exists)
    CASE
        WHEN fr.status = 'pending' AND fr.sender_id = $2 THEN 'sent'
        WHEN fr.status = 'pending' AND fr.receiver_id = $2 THEN 'received'
        ELSE fr.status
    END as friend_request_direction,
    
    -- Friendship status (if exists)
    CASE 
        WHEN f.user1_id IS NOT NULL THEN true
        ELSE false
    END as is_friend
    
FROM users u

LEFT JOIN friend_requests fr 
    ON (fr.sender_id = $2 AND fr.receiver_id = u.user_id)
    OR (fr.sender_id = u.user_id AND fr.receiver_id = $2)

LEFT JOIN friendships f
    ON (f.user1_id = LEAST($2, u.user_id) AND f.user2_id = GREATEST($2, u.user_id))

WHERE u.uuid = $1
`

type GetUserByUUIDParams struct {
	Uuid     uuid.UUID `json:"uuid"`
	SenderID int64     `json:"sender_id"`
}

type GetUserByUUIDRow struct {
	UserID                 int64       `json:"user_id"`
	Uuid                   uuid.UUID   `json:"uuid"`
	DisplayName            string      `json:"display_name"`
	FriendRequestDirection interface{} `json:"friend_request_direction"`
	IsFriend               bool        `json:"is_friend"`
}

// Get user info with friendship/friend request status
// $1: target_user_uuid (user being searched)
// $2: current_user_id (user doing the search)
// Check if there's a pending/accepted friend request
// Check if already friends
func (q *Queries) GetUserByUUID(ctx context.Context, arg GetUserByUUIDParams) (GetUserByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, arg.Uuid, arg.SenderID)
	var i GetUserByUUIDRow
	err := row.Scan(
		&i.UserID,
		&i.Uuid,
		&i.DisplayName,
		&i.FriendRequestDirection,
		&i.IsFriend,
	)
	return i, err
}
