version: "3.8"

services:
  db:
    image: postgres:18.2-alpine3.23
    container_name: postgres-db-chat-app
    restart: unless-stopped

    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres-data-chat-app:/var/lib/postgresql/data

  redis:
    image: redis:8.6.2-alpine
    container_name: redis-chat-app
    restart: unless-stopped
    ports:
      - "6380:6379"
    command:
      [
        "redis-server",
        "--save",
        "900",
        "1",
        "--save",
        "300",
        "10",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    volumes:
      - redis-data-chat-app:/data

volumes:
  postgres-data-chat-app:
  redis-data-chat-app:
